application:
  park-code: shikou
netty:
  url: 0.0.0.0
  port: 8001
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.99.61:5432/hj212_monitor?useSSL=false
          username: marc
          password: testtest2016
        environmental:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.99.25:3306/hj212_monitor?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
  devtools:
    add-properties: false